### ISSUE TITLE
Reverse angle for spawning

### ISSUE THREAD

**Issue by Samuel-Roach** [PGMDev/PGM#1062] opened 2022-09-26 18:07 UTC
Add an attribute for ``reverse-angle`` in the spawns tag. This would be mutually exclusive to ``angle``.

Typical use case:
In OBS spawns you want observers to be able to spawn looking out in different directions, and currently without implementing multiple regions there's no clean way to do this. 

As ``angle`` was implemented to reduce the need for multiple ``yaw``'s when having many spawns facing the same central point, this would be implemented to provide the opposite.

```xml
<spawns>
    <spawn team="red" kit="red" angle="158.5,7,-1.5">
        <cuboid min="154.5,6,-5.5" max="156.5,7,-3.5"/>
    </spawn>
    ...
    <default reverse-angle="126.5,33,25.5">
        <cuboid min="120.5,32,24.5" max="122.5,33,26.5"/>
    </default>
</spawns>
```

**Comment by Pablete1234** [comment] 2022-09-26 20:40
Duplicate of #920

**Closed as completed by Pablete1234** 2022-09-26 20:40 UTC
