### ISSUE TITLE
Implement indepent capture times 

### ISSUE THREAD

**Issue by lefckntea** [PGMDev/PGM#898] opened 2021-07-08 04:49 UTC
For other gamemode ideas like one similar to Overwatch's Control gamemode independent capture times of a capture point could be quite useful.
This means that a teams start at 0% when they capture a point, without them needing to uncapture the enemy progress on that hill. 
Should then also display in scoreboard seperately

**Comment by CoWinkKeyDinkInc** [comment] 2021-09-05 02:40
https://overwatch.fandom.com/wiki/Control

>On Control, two teams fight over a series of objective areas in a best-of-three format. This means that there is no distinction to attacking or defending teams like in other game modes.[1]

>Once the match has started and both teams have left the spawn, the control point takes 30 seconds to unlock. Once it unlocks, the objective area can be captured by either team. To capture the checkpoint, members of only one team must stand on the point for a given time, speed increasing with the number of teammates present. Note that the objective cannot be captured if a member of the enemy team is also on the control point. Once captured, the team must defend the point, while the other must gain control of the area by driving the enemies out and capturing it themselves. The objective score will progress 1% every 1.2 seconds in favor of the team controlling the point. The round is won once one team reaches 100%. If a member of the non-controlling team touches the point when the score hits 99% or shortly before, Overtime will be activated. The first team to win two rounds wins the match. 

Essentially the capture progress will be saved and cannot be reversed, this should be very easy to implement.

**Comment by Pablete1234** [comment] 2021-09-05 05:14
This was discussed in discord a while ago, the conversation can be found at: https://discord.com/channels/730855489767997511/730857379729506335/862599813391188019

The TLDR if my hill-based solution was:
Make 3 hills.
One is a hidden control, that decides what team is holding the point.
Filtered based on who controls that hill, either one team or another team hill is allowed to progress.
You may need a 4th (hidden) hill as win condition that gets capped instantly by whoever gets to 100% 

For a simpler solution:
You can just have one normal hill that can be captured by one team or the other, and make it award one score per second. First team to 100 score wins.

**Comment by Pablete1234** [comment] 2021-09-19 07:17
@lefckntea i'm going to close this issue for now as it doesn't really look like an issue with pgm, it's not a bug nor a missing feature, since already possible to do with multiple hills (which is basically what you're asking for, multiple hills working as multiple hills)

**Closed as completed by Pablete1234** 2021-09-19 07:17 UTC
