### ISSUE TITLE
Tablist entities showing with TAB in chat.

### ISSUE THREAD

**Issue by KingOfSquares** [PGMDev/PGM#416] opened 2020-04-20 12:28 UTC
![2020-04-20_02 10 14](https://user-images.githubusercontent.com/19822231/79751441-de45fc80-8312-11ea-8a51-cae6ecdb49cb.png)

I'm guessing this is present on all versions past 1.13, since this is when [Brigadier](https://minecraft.gamepedia.com/Brigadier) was introduced.

**Comment by Pablete1234** [comment] 2020-04-20 13:16
Technically not a bug, and can't be fixed. Best bet is to just make sure the start with a "high-value" character so they're placed at the end

**Comment by Electroid** [comment] 2020-04-20 16:25
We should try to mitigate this as best as we can.

**Comment by TiTo418** [comment] 2020-08-14 11:24
Fixed in #588

**Closed** 2020-08-14 11:30 UTC
Labels: bug
