### ISSUE TITLE
Custom projectile cooldown not respected after switching teams

### ISSUE THREAD

**Issue by willocn** [PGMDev/PGM#1285] opened 2023-12-17 23:40 UTC
When you switch teams during a match, projectile cooldown is not respected. Projectile works as expected if you switch back to the original team.

**Steps to reproduce**
1. Join a team
2. Switch teams
3. Observe that you can shoot projectiles instantly

This doesn't happen on FFA matches.

https://github.com/PGMDev/PGM/assets/88864994/d41b93c5-18de-49a6-a90e-b23c4a66b5a8

**Comment by Pugzy** [comment] 2023-12-17 23:54
Caused by the following code which always sets the cooldown to be ended if the player team states don't match.
https://github.com/PGMDev/PGM/blob/12e9e602e3b7b3064d8a302719f5f5d5d4885ab7/core/src/main/java/tc/oc/pgm/projectile/CooldownRunnable.java#L24

Looks like cooldowns are stored for a player on each team they join but due to equal checks they always use the expired one.

**Comment by Pablete1234** [comment] 2024-04-27 16:34
Fixed in #1297

**Closed as completed by Pablete1234** 2024-04-27 16:34 UTC
