### ISSUE TITLE
Incompatibility of using Bold Prefixes (Probably suffixes too)

### ISSUE THREAD

**Issue by IcedCode** [PGMDev/PGM#615] opened 2020-08-16 23:07 UTC
If you use "&l" in a prefix, the prefix will work in the chat however it will not work and format the prefix white (ignoring any other chat formatting) in the tablist, administrative commands & end of match stats.

Looking at it, the problem seems to be with the PlayerComponent Class.

Image below shows what works and what doesn't.
![image](https://user-images.githubusercontent.com/7426927/90346020-7199f080-dfda-11ea-8409-cb1b070878f3.png)

**Comment by applenick** [comment] 2020-08-16 23:17
[This](https://github.com/PGMDev/PGM/blob/70c139f3094195b68477180bce7ab645a9e6267b/util/src/main/java/tc/oc/pgm/util/text/types/PlayerComponent.java#L211) is most likely the cause of the issue with rendering. And further [this](https://github.com/PGMDev/PGM/blob/dev/util/src/main/java/tc/oc/pgm/util/text/TextFormatter.java#L129) method, is what’s having trouble. I may have forgotten to take TextDecorations into account 😅. I’ll see if a fix for this can possibly be added to #608

**Closed as completed** 2020-08-19 15:33 UTC
Labels: bug
