### ISSUE TITLE
Add replace sub element for item inside kits

### ISSUE THREAD

**Issue by lefckntea** [PGMDev/PGM#1033] opened 2022-07-15 00:28 UTC
This would allow you to give an item which replaces another item the player already had in his inventory instead of only being able to give it in specific slots
```
<item ... >
 <replace><item ...>...</item></replace>
</item> 
```
Got this from the pgm discord, i think its important so i make issue.

**Comment by Pablete1234** [comment] 2022-07-15 00:42
Syntax i proposed for this was:

```xml
<kit id="upgrade-sword">
  <item material="diamond sword" replace="iron sword"/>
</kit>
```
What's new in this syntax is just the `replace` with a single material pattern (eg: allowing for wool:15).
There are concerns over this specific format like being able to define in a more fine-grained way what item it should replace, like maybe you want to replace specific-enchantment-item, but i'm not sure what the demand for those are.
Generally it'd be good to have filters which can query on an item and allow/deny based on metadata (enchants, lore, amount,durability) instead of just material, but i don't think we're there yet. If we had such filters, the `replace` property could be replaced with a `replace-filter` which takes such a filter and searches the inventory for the item, replace and replace-filter would be mutually exclusive (only one must be set).

**Comment by lefckntea** [comment] 2022-07-15 00:46
the way i wanna use it, i'm not sure if it needs to check for enchantments.
like if i wanna replace a normal bow with an enchanted bow and then replace it back i dont need to check for enchantments on replace cause theres only 1 bow at a time in the players inventory right?

i have no clue about any other use cases tho, maybe they need it

if its being done with a sub element instead of an attribute what meta data could it check for rn that wouldnt require creating filters like u said

**Comment by RuedigerLP** [comment] 2022-07-15 11:51
Might be a duplicate of https://github.com/PGMDev/PGM/issues/234?

**Comment by lefckntea** [comment] 2022-07-15 11:55
> Might be a duplicate of #234?

oh it is. i don't know why i didn't find it when i searched for replace.
tho to your comment on that issue about if the new item should be given or not if the player does not have the specified item: i think that should be an option inside the sub element. both versions could have use cases but idk how other people would use this feature

**Closed as completed** 2022-07-15 12:00 UTC
