### ISSUE TITLE
Slugs (map IDs) are prioritised over map names when it doesn't make sense to do so

### ISSUE THREAD

**Issue by calcastor** [PGMDev/PGM#1377] opened 2024-08-05 00:35 UTC
Slugs are used to maintain a map's ID across different names in a database. With the command `/map`, exact string matches to a map's slug will resolve to that map: for instance `/map coastline` on OCC will resolve to `Coastline: Classic`.

Following 8ceb97834f506bfbce84d29dd810b9ccce6d1991, this has extended to map pools (not exactly correct, see https://github.com/PGMDev/PGM/issues/1377#issuecomment-2267975193). This is problematic given that map pools have, until this commit, resolved against name only. To use `Coastline` as an example again, we list this map in our default map pool on OCC; prior to this commit, the map that was in the pool was `Coastline` which has a slug of `coastline_redux`, and now it is `Coastline: Classic` which has a slug of `coastline`.

There are very little situations in which it is appropriate for slug to take precedence over a map's name. Slugs should function as an internal mechanism only to avoid conflicts between maps in a database. Having slugs take precedence in situations that I have outlined above makes map pools more difficult to maintain and confuses end users and players.

Resolving this issue will require consideration for computational expense. Matching against ID is quick as, typically, a slugified map name is directly connected to that map because most maps do not have an explicitly defined slug. See the following screenshot for some further context:
<img width="1135" alt="image" src="https://github.com/user-attachments/assets/8178cf87-8b30-4a18-a034-c308773c8d00">

**Comment by Pablete1234** [comment] 2024-08-05 00:38
> Following https://github.com/PGMDev/PGM/commit/8ceb97834f506bfbce84d29dd810b9ccce6d1991, this has extended to map pools. This is problematic given that map pools have, until this commit, resolved against name only.

Just to clarify, this has **always** been the behavior of pgm resolving maps everywhere. The only changes is that now the variants are actually getting the slugs you were defining while before it wasn't working as intended

Relevant code here is: https://github.com/PGMDev/PGM/blob/dev/core/src/main/java/tc/oc/pgm/map/MapLibraryImpl.java#L56

If you compare that with the original version, it's essentially the same logic (just a bit cleaner and modified over the years):
![image](https://github.com/user-attachments/assets/d5e79a65-2ef9-493e-821d-f400e2156a77)

**Comment by TTtie** [comment] 2024-08-05 11:44
I'm gonna drop my [0.5 CZK](https://www.xe.com/currencyconverter/convert/?Amount=0.02&From=EUR&To=CZK) here.

Sure, map name should be prioritized over map slug in user-facing commands (i. e. `/map`, `/maps`, etc.). In fact, matching by name only would probably also be OK. This, however, has the following implication:

In current PGM, duplicate map names are **perfectly legal** (you might encounter issues with user confusion and tab completion, but that's about it). This makes slugs very useful in conflict resolution, for example in development environments where it might be desirable to have a development version loaded in parallel to the production version:
   
![A screenshot showing a listing of maps named "BlockGlitch", showing "BlockGlitch 4" by Flamiix twice](https://github.com/user-attachments/assets/7dedf000-bef7-4052-b61f-432327db2ffb)
*A screenshot showing a listing of maps named "BlockGlitch", showing "BlockGlitch 4" by Flamiix twice. The only difference between those two BlockGlitch 4 maps is the source repository and the map slug.*

Or, as a heavily exaggerated example: 

There may just happen to be a radically different DTM (possibly a larger, or a smaller) Coastline map built for PGM by the map developers over at `::1`. They might not know that a Coastline already exists on OCC. They might, in fact, not know that OCC exists at all!
  
However, one day, a high-ranking staff member over at `::1` discovers OCC, and they found OCC's Coastline to be so good that they include it over at `::1`. The map developers at `::1` thought of such a situation beforehand and decided to prefix all of their maps' slugs with `0__1_`, i. e. `0__1_coastline` for their Coastline map. The staff at `::1` are able to load their and also OCC's Coastline with zero XML/database changes and everyone is happy!

---

In map pools, however, matching by slug first (i. e. keeping the current behavior) should be preserved, or even better, map pools should be matched **only** by slug. This might hurt readability for the average user, but:
- Map pools are a configuration file. Configuration files should not contain ambiguous references. Map names, as seen above, are ambiguous. Map slugs aren't, as they are unique for every map. If preserving transparency is desired and the map slug happens to be radically different, a comment may be added to tell the world which map it actually is.
- This follows the already established practice of [map proto 1.4](https://pgm.dev/docs/modules/general/proto#changes-in-140) using an unique feature ID over a (possibly duplicate) name.

**Closed as completed** 2024-08-07 20:55 UTC
